# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BooksSearchongDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BooksSearchongDemo
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Nuke'

  target 'BooksSearchongDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BooksSearchongDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
